name: Feature Request
description: Suggest a new feature for the QKD Failure Detection System
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees:
  - arnav

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
      
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component would this feature affect?
      options:
        - QKD Simulator
        - Anomaly Detector
        - ML Detector
        - Signal Analyzer
        - Security Monitor
        - Utilities
        - Tests
        - Documentation
        - New Component
        - Multiple Components
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Essential for project)
        - High (Important for users)
        - Medium (Nice to have)
        - Low (Enhancement)
    validations:
      required: true
      
  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (Simple change)
        - Medium (Moderate implementation)
        - High (Complex feature)
        - Unknown
        
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: How would you use this feature? What problem does it solve for you?
    validations:
      required: true
      
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be implemented for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
        
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: This feature aligns with the project's goals
          required: true
