name: Research Question
description: Ask a research-related question about QKD or quantum cryptography
title: "[RESEARCH] "
labels: ["research", "question"]
assignees:
  - arnav

body:
  - type: markdown
    attributes:
      value: |
        Welcome to the research discussion! Please ask your question about QKD, quantum cryptography, or the detection algorithms.
        
  - type: textarea
    id: question
    attributes:
      label: Research Question
      description: What is your research question?
      placeholder: Please describe your question in detail...
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Research Category
      description: Which area does your question relate to?
      options:
        - Quantum Key Distribution Protocols
        - Quantum Cryptography Security
        - Machine Learning in Quantum Systems
        - Anomaly Detection Algorithms
        - Signal Processing for Quantum Systems
        - Attack Detection and Prevention
        - Performance Optimization
        - Mathematical Foundations
        - Experimental Implementation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Background Context
      description: Provide any relevant background or context for your question
      placeholder: What have you already researched? What specific aspect are you trying to understand?
    validations:
      required: true
      
  - type: textarea
    id: current_understanding
    attributes:
      label: Current Understanding
      description: What is your current understanding of the topic?
      placeholder: Share what you already know or think you know about this topic...
      
  - type: textarea
    id: references
    attributes:
      label: Relevant References
      description: Any papers, books, or resources you've already consulted?
      placeholder: List any relevant papers, articles, or resources...
      
  - type: dropdown
    id: level
    attributes:
      label: Technical Level
      description: What is your technical background in this area?
      options:
        - Beginner (New to the field)
        - Intermediate (Some background knowledge)
        - Advanced (Experienced in the field)
        - Expert (Research-level understanding)
        
  - type: textarea
    id: application
    attributes:
      label: Intended Application
      description: How do you plan to apply this knowledge?
      placeholder: Research project, thesis, implementation, general understanding, etc.
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: My question is related to the project or quantum cryptography
          required: true
        - label: I have provided sufficient context for my question
          required: true
