# QKD Failure Detection System - Default Configuration

# QKD Simulation Parameters
qkd:
  protocol: "BB84"
  key_length: 1000
  noise_level: 0.05
  channel_loss: 0.1
  detector_efficiency: 0.8
  dark_count_rate: 1e-6

# Anomaly Detection Parameters
anomaly_detection:
  qber_threshold: 0.11
  statistical_method: "control_chart"
  window_size: 50
  outlier_detection: "z_score"
  confidence_level: 0.95

# Machine Learning Parameters
ml_detection:
  model_type: "random_forest"
  n_estimators: 100
  max_depth: 10
  test_size: 0.2
  cross_validation_folds: 5
  feature_scaling: true

# Signal Analysis Parameters
signal_analysis:
  sampling_rate: 1e9  # 1 GHz
  fft_size: 1024
  window_function: "hann"
  spectral_method: "welch"
  noise_floor: -80  # dB

# Security Monitoring Parameters
security_monitoring:
  attack_detection_threshold: 0.15
  information_leakage_limit: 0.01
  monitoring_window: 100
  alert_sensitivity: "medium"

# Performance Parameters
performance:
  real_time_processing: true
  max_latency_ms: 50
  memory_limit_mb: 100
  cpu_cores: 4

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/qkd_system.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size: "10MB"
  backup_count: 5

# Visualization Parameters
visualization:
  plot_style: "seaborn"
  figure_size: [10, 6]
  dpi: 300
  save_format: "png"
  color_palette: "viridis"

# Data Management
data:
  output_directory: "results"
  cache_directory: "data/processed"
  example_data_path: "data/examples"
  auto_cleanup: true
  max_cache_size_gb: 1
